database:
  driverClass: org.h2.Driver
  user: inko
  password: s3cr3T_
  url: jdbc:h2:./rom-database
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080
    
logging:
  level: INFO
  loggers:
    app.kflow: DEBUG
    org.hibernate.SQL: ALL
  appenders:
    - type: console